name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Header & Community Stats
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, community, metadata
          config_timezone: UTC
         # This shows the logos of organizations you belong to or help
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request
          plugin_organizations: yes
          plugin_organizations_limit: 10

      # Detailed Language Analysis (Past Year)
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "" # No header, just the plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_sections: recently-used, most-used
          plugin_languages_indepth: yes
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 3000
          plugin_languages_aliases: "TSX:TypeScript, JSX:JavaScript" # Merges TSX into TypeScript
          plugin_languages_ignored: html, css, scss, shell, d, makefile, dockerfile, markdown # Hide the "noise" languages
          plugin_languages_threshold: 2%
          commits_authoring: Cooksey99, andrewcooksey42@gmail.com, acooksey@actota.com, acooksey@beconsocial.com

      # Open Source & Notable Contributions
      - uses: lowlighter/metrics@latest
        with:
          filename: open-source.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request
          plugin_followup: yes
          plugin_followup_sections: user

      # Isometric Calendar (Your existing one)
      - uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # Indepth Analysis
      - uses: lowlighter/metrics@latest
        with:
          filename: indepth-analysis.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
